### ISSUE TITLE
[4.0.6 RC] Can't save tax setting

### ISSUE THREAD

**Issue by Heart1010** [PhocaCz/PhocaCart#149]
Installed v4.0.6RC and imported the demo data.
Now I want to change the tax name from VAT to MWST but when clicking SAVE button I get this error message:

![image](https://user-images.githubusercontent.com/1481680/223663483-1b1bf9b3-2c79-413b-8c26-8fd8f9446aac.png)

**Comment by PhocaCz** [comment]
Hi, it seems like there is wrong column structure.

Are you able to change it, e.g. in phpMyAdmin?  Just run this SQL query:

```ALTER TABLE `#__phocacart_taxes` CHANGE `tax_hide` `tax_hide` text;```

Change the #__ prefix to your own, in your case to j51bi_phocacart_taxes

And let me know.

Thank you, Jan

**Comment by Heart1010** [comment]
Thanks, Jan - that worked 👍 

P.S.: tax_hide was tinyint(1) after installing v4.0.6rc

**Comment by PhocaCz** [comment]
Hi, yes, this was wrong, should be "text", I have changed it in RC

install.utf8.sql
![img](https://i.imgur.com/8cxetxC.png)

4.0.6.sql
![img](https://i.imgur.com/EpBa86Q.png)

It is fixed here:
https://github.com/PhocaCz/PhocaCart/releases/download/4.0.6RC/com_phocacart_v4.0.6RC.zip
but of course, reinstalling does not have any effect (because the column is included in database and upgrade does not change it - so it is needed to fix it in database)
